openapi: 3.0.3
info:
    title: Receptkezelő webalkalmazás Api
    description: TODO
    contact:
        name: Máté Zsolt Sándor
        email: mzsoltsandor@gmail.com
    license:
        name: MIT
        url: https://opensource.org/licenses/MIT
    version: v0.0.0-dev
#servers: TODO
tags:
  - name: Alive
    description: Service Alive Controller
  - name: Recipes
paths:
    /alive/:
      get:
        tags:
          - Alive
        summary: Sends a report about the availability of services.
        operationId: getServiceReport
        responses:
          200:
            description: Report is sent back
    /recipes/:
      post:
        tags:
          - Recipes
        summary: Creates a recipe
        operationId: createRecipe
        responses:
          201:
            description: Recipe created successfully
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/createRecipeDTO'
components:
  schemas:
    createRecipeDTO:
      title: createRecipeDTO
      type: object
      properties:
        title:
          type: string
          description: The title of the new recipe
        description:
          type: string
          description: Simple description of the recipe
        steps:
          type: array
          description: List of steps to make the recipe
          items:
            type: string
            description: Steps to make a recipe
        

